[package]
name = "rust-workshop-2"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "bench"
harness = false

[dev-dependencies]
criterion = "0.6.0"

[dependencies]
hdf5 = { package = "hdf5-metno", version = "0.10.1", features = ["static"] }
ndarray = "0.16.1"
